=== radec94/mini-erp/xml i xsd/albara.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="albara" type="tipusAlbara"/>
  
  <xs:complexType name="tipusAlbara">
    <xs:sequence>
      <xs:element name="codiComanda" type="tipusCodi"/>
      <xs:element name="data" type="xs:date"/>
      <xs:element name="articles" type="tipusArticles"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:simpleType name="tipusCodi">
    <xs:restriction base="xs:string">
      <xs:length value="4"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="tipusArticles">
    <xs:sequence>
      <xs:element name="article" type="tipusArticle"  minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="tipusArticle">
    <xs:sequence>
      <xs:element name="codiArticle" type="tipusCodiArticle"/>
      <xs:element name="quantitat" type="xs:int"/>
      <xs:element name="preu" type="xs:int"/>
      <xs:element name="rebut" type="tipusRebut"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="tipusCodiArticle">
    <xs:restriction base="xs:string">
      <xs:length value="4"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipusRebut">
    <xs:restriction base="xs:string">
      <xs:pattern value="Si|No"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== radec94/mini-erp/xml i xsd/C2A1.xml
<?xml version="1.0" encoding="utf-8"?>
<albara xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="albara.xsd">  
    <codi>0001</codi>
    <data>21/05/2015</data>
    <articles>
        <article>
            <codiArticle>0001</codiArticle>
            <quantitat>7</quantitat>
            <preu>20</preu>
        </article>
        <article>
            <codiArticle>0002</codiArticle>
            <quantitat>10</quantitat>
            <preu>19</preu>
        </article>
        <article>
            <codiArticle>0004</codiArticle>
            <quantitat>2</quantitat>
            <preu>15</preu>
        </article>
        <article>
            <codiArticle>0006</codiArticle>
            <quantitat>10</quantitat>
            <preu>24</preu>
        </article>
        <article>
            <codiArticle>0008</codiArticle>
            <quantitat>5</quantitat>
            <preu>30</preu>
        </article>
        <article>
            <codiArticle>0010</codiArticle>
            <quantitat>11</quantitat>
            <preu>11</preu>
        </article>
        <article>
            <codiArticle>0012</codiArticle>
            <quantitat>13</quantitat>
            <preu>14</preu>
        </article>
        <article>
            <codiArticle>0014</codiArticle>
            <quantitat>4</quantitat>
            <preu>37</preu>
        </article>    
    </articles>
</albara>
