=== radec94/mini-erp/xml i xsd/articles.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="articles" type="tipusArticles"/>
  <xs:complexType name="tipusArticles">
    <xs:sequence>
      <xs:element name="article" type="tipusArticle" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

    <xs:complexType name="tipusArticle">
    <xs:sequence>
      <xs:element name="codi" type="tipusCodi"/>
	    <xs:element name="descripcio" type="xs:string"/>
	    <xs:element name="preu" type="xs:int"/>
	    <xs:element name="estoc" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="tipusCodi">
      <xs:restriction base="xs:string">
        <xs:length value="4"/>
      </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== radec94/mini-erp/xml i xsd/articles.xml
<?xml version="1.0"?>
<articles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="articles.xsd">
	<article>
        <codi>0001</codi>
        <descripcio>Motxilla blava esportiva</descripcio>
		    <preu>20</preu>
        <estoc>245</estoc>
	</article>
	<article>
		    <codi>0002</codi>
        <descripcio>Samarreta de quadres vermell i blanc</descripcio>
		    <preu>19</preu>
        <estoc>124</estoc>
	</article>
	<article>
		    <codi>0003</codi>
        <descripcio>Pantalons negres cagats</descripcio>
		    <preu>25</preu>
        <estoc>432</estoc>
	</article>
	<article>
		    <codi>0004</codi>
        <descripcio>Chandall esportiu blau i blanc</descripcio>
		    <preu>15</preu>
        <estoc>214</estoc>
	</article>
	<article>
		    <codi>0005</codi>
        <descripcio>Mitjons curts negres</descripcio>
		    <preu>7</preu>
        <estoc>227</estoc>
	</article>
	<article>
		    <codi>0006</codi>
        <descripcio>Texans blaus curts</descripcio>
	    	<preu>24</preu>
        <estoc>373</estoc>
	</article>
	<article>
	    	<codi>0007</codi>
        <descripcio>Jaqueta negra</descripcio>
	    	<preu>40</preu>
        <estoc>174</estoc>
	</article>
	<article>
	    	<codi>0008</codi>
        <descripcio>Polar vermell</descripcio>
		    <preu>30</preu>
        <estoc>319</estoc>
	</article>
	<article>
	    	<codi>0009</codi>
        <descripcio>Espardenyes estiu marrons</descripcio>
		    <preu>12</preu>
        <estoc>259</estoc>
	</article>
	<article>
		    <codi>0010</codi>
        <descripcio>Botes d'aigua blaves</descripcio>
		    <preu>11</preu>
        <estoc>381</estoc>
	</article>
	<article>
		    <codi>0011</codi>
        <descripcio>Sandalies estiu marrons</descripcio>
	    	<preu>11</preu>
        <estoc>256</estoc>
	</article>
	<article>
		    <codi>0012</codi>
        <descripcio>Bambes esportives negres</descripcio>
	    	<preu>14</preu>
        <estoc>155</estoc>
	</article>
	<article>
	    	<codi>0012</codi>
        <descripcio>Camiseta groga</descripcio>
		    <preu>12</preu>
        <estoc>179</estoc>
	</article>
	<article>
	    	<codi>0013</codi>
        <descripcio>Suadera blanca</descripcio>
	    	<preu>37</preu>
        <estoc>264</estoc>
	</article>
	<article>
		    <codi>0014</codi>
        <descripcio>Paravent vermell</descripcio>
	    	<preu>32</preu>
        <estoc>375</estoc>
	</article>
	<article>
		    <codi>0015</codi>
        <descripcio>Xubasquero blau</descripcio>
	    	<preu>28</preu>
        <estoc>225</estoc>
	</article>
	<article>
		    <codi>0016</codi>
        <descripcio>Camisa llisa blau fosc</descripcio>
		    <preu>21</preu>
        <estoc>312</estoc>
	</article>
	<article>
	    	<codi>0017</codi>
        <descripcio>Malles negres</descripcio>
		    <preu>11</preu>
        <estoc>231</estoc>
	</article>
	<article>
		    <codi>0018</codi>
        <descripcio>Chaleco marro</descripcio>
	    	<preu>34</preu>
        <estoc>395</estoc>
	</article>
	<article>
		    <codi>0019</codi>
        <descripcio>Forro polar negre</descripcio>
		    <preu>42</preu>
        <estoc>278</estoc>
	</article>
</articles>
