=== radec94/mini-erp/xml i xsd/comandes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="comanda" type="tipusComanda"/>

  <xs:complexType name="tipusComanda">
    <xs:sequence>
      <xs:element name="codiProveidor" type="xs:string"/>
      <xs:element name="data" type="xs:string"/><!--Ficar tipus date-->
      <xs:element name="articles" type="tipusArticles"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipusArticles">
    <xs:sequence>
      <xs:element name="article" type="tipusArticle"  minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="tipusArticle">
    <xs:sequence>
      <xs:element name="codiArticle" type="xs:string"/>
      <xs:element name="quantitat" type="xs:string"/>
      <xs:element name="preu" type="xs:string"/>
      <xs:element name="rebut" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== radec94/mini-erp/xml i xsd/comanda1.xml
<?xml version="1.0" encoding="utf-8"?>
<comanda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="comandes.xsd">
    <codiProveidor>P03</codiProveidor>
    <data>2015-09-24</data><!--Ha de estar amb aquest format: 2002-09-24 -->
    <articles>
        <article>
            <codiArticle>0001</codiArticle>
            <quantitat>8</quantitat>
            <preu>20</preu>
            <rebut>No</rebut>
        </article>
        <article>
            <codiArticle>0003</codiArticle>
            <quantitat>12</quantitat>
            <preu>25</preu>
            <rebut>No</rebut>
        </article>
        <article>
            <codiArticle>0005</codiArticle>
            <quantitat>5</quantitat>
            <preu>7</preu>
            <rebut>No</rebut>
        </article>
        <article>
            <codiArticle>0007</codiArticle>
            <quantitat>10</quantitat>
            <preu>40</preu>
            <rebut>No</rebut>
        </article>
        <article>
            <codiArticle>0009</codiArticle>
            <quantitat>17</quantitat>
            <preu>12</preu>
            <rebut>No</rebut>
        </article>
        <article>
            <codiArticle>0011</codiArticle>
            <quantitat>14</quantitat>
            <preu>11</preu>
            <rebut>No</rebut>
        </article>
        <article>
            <codiArticle>0013</codiArticle>
            <quantitat>16</quantitat>
            <preu>12</preu>
            <rebut>No</rebut>
        </article>
        <article>
            <codiArticle>0015</codiArticle>
            <quantitat>5</quantitat>
            <preu>32</preu>
            <rebut>No</rebut>
        </article>
    </articles>
</comanda>
