=== radec94/mini-erp/xml i xsd/proveidors.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="proveidors" type="tipusProveidors"/>

  <xs:complexType name="tipusProveidors">
    <xs:sequence>
      <xs:element name="proveidor" type="tipusProveidor" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="tipusProveidor">
    <xs:sequence>
      <xs:element name="codi" type="xs:string"/>
      <xs:element name="nom" type="xs:string"/>
      <xs:element name="adreca" type="xs:string"/>
      <xs:element name="poblacio" type="xs:string"/>
      <xs:element name="cp" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== radec94/mini-erp/xml/proveidors.xml
<?xml version="1.0" encoding="UTF-8"?>
<proveidors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="proveidors.xsd">
	<proveidor>
		<codi>P01</codi>
		<nom>Gemma</nom>
		<adreca>c/prineu</adreca>
		<poblacio>Girona</poblacio>
		<cp>17070</cp>
	</proveidor>
	<proveidor>
		<codi>P02</codi>
		<nom>Mariel</nom>
		<adreca>c/pau</adreca>
		<poblacio>Girona</poblacio>
		<cp>17001</cp>
	</proveidor>
	<proveidor>
		<codi>P03</codi>
		<nom>Harlequin</nom>
		<adreca>c/president</adreca>
		<poblacio>Girona</poblacio>
		<cp>17005</cp>
	</proveidor>
	<proveidor>
		<codi>P04</codi>
		<nom>Peroni</nom>
		<adreca>c/palau</adreca>
		<poblacio>Girona</poblacio>
		<cp>17071</cp>
	</proveidor>
	<proveidor>
		<codi>P05</codi>
		<nom>Mimic</nom>
		<adreca>c/pla√ßa</adreca>
		<poblacio>Girona</poblacio>
		<cp>17002</cp>
	</proveidor>
</proveidors>
